# Generated by Django 5.2 on 2025-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('cuit', models.CharField(db_index=True, max_length=11)),
                ('aseguradora', models.CharField(db_index=True, max_length=120)),
                ('razon_social', models.CharField(max_length=255)),
                ('contrato', models.BigIntegerField(blank=True, null=True)),
                ('deuda_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('q_periodos_deudores', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado_contrato', models.CharField(max_length=60)),
                ('email_del_trato', models.CharField(blank=True, max_length=255, null=True)),
                ('no_contactar', models.BooleanField(default=False)),
                ('productor', models.CharField(default='PROMECOR', max_length=120)),
                ('premier', models.CharField(choices=[('Premier', 'Premier'), ('No es Premier', 'No es Premier')], max_length=20)),
                ('cliente_importante', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'art_consolidado',
                'indexes': [models.Index(fields=['periodo', 'aseguradora'], name='art_consoli_periodo_8db167_idx'), models.Index(fields=['periodo', 'cuit'], name='art_consoli_periodo_d2fff6_idx')],
                'unique_together': {('periodo', 'cuit', 'aseguradora')},
            },
        ),
    ]
