# Generated by Django 5.2 on 2025-08-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo_maestro', models.CharField(blank=True, max_length=255)),
                ('archivos_fuente', models.JSONField(blank=True, default=dict)),
                ('ruta_excel_salida', models.CharField(blank=True, max_length=500)),
                ('filas_consolidado', models.PositiveIntegerField(default=0)),
                ('filas_no_cruzan', models.PositiveIntegerField(default=0)),
                ('hash_entrada', models.CharField(blank=True, db_index=True, max_length=64)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_consolidado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'art_consolidado_lote',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(db_index=True, max_length=20)),
                ('periodo', models.DateField(null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('aseguradora', models.CharField(db_index=True, max_length=120)),
                ('contrato', models.CharField(blank=True, max_length=60)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('q_periodos_deudores', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado_contrato', models.CharField(blank=True, max_length=60)),
                ('email_del_trato', models.CharField(blank=True, max_length=255)),
                ('no_contactar', models.BooleanField(default=False)),
                ('productor', models.CharField(default='PROMECOR', max_length=120)),
                ('premier', models.CharField(blank=True, choices=[('Premier', 'Premier'), ('No es Premier', 'No es Premier')], default='No es Premier', max_length=20)),
                ('cliente_importante', models.BooleanField(default=False)),
                ('en_deuda', models.BooleanField(default=True)),
                ('hoja', models.CharField(choices=[('consolidado', 'Consolidado'), ('no_cruzan', 'No cruzan'), ('productor', 'Productor')], default='consolidado', max_length=20)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='art.consolidadolote')),
            ],
            options={
                'db_table': 'art_consolidado_item',
                'indexes': [models.Index(fields=['cuit', 'periodo'], name='art_consoli_cuit_81b109_idx'), models.Index(fields=['aseguradora'], name='art_consoli_asegura_4ac5e6_idx'), models.Index(fields=['hoja'], name='art_consoli_hoja_c5e94b_idx')],
                'unique_together': {('lote', 'cuit', 'aseguradora', 'contrato', 'periodo', 'hoja')},
            },
        ),
        migrations.CreateModel(
            name='EnvioEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuit', models.CharField(db_index=True, max_length=20)),
                ('aseguradora', models.CharField(blank=True, max_length=120)),
                ('contrato', models.CharField(blank=True, max_length=60)),
                ('destinatarios', models.JSONField(blank=True, default=list)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo_resumen', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('excluido', 'Excluido')], default='enviado', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lote_consolidado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.consolidadolote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'art_envio_email_log',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['cuit', 'creado_en'], name='art_envio_e_cuit_8c9f86_idx'), models.Index(fields=['estado'], name='art_envio_e_estado_547335_idx')],
            },
        ),
    ]
