# Generated by Django 5.2 on 2025-08-26 17:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_consolidadolote_consolidadoitem_envioemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtDashboardContratoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes del consolidado (ej: 2025-06-01).')),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('cuit', models.CharField(db_index=True, max_length=20)),
                ('contrato', models.CharField(db_index=True, max_length=50)),
                ('aseguradora', models.CharField(db_index=True, max_length=120)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('costo_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('q_periodos_deudores', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estado_contrato', models.CharField(blank=True, default='', max_length=60)),
                ('email_trato', models.CharField(blank=True, default='', max_length=200)),
                ('no_contactar', models.BooleanField(default=False)),
                ('productor', models.CharField(blank=True, default='', max_length=120)),
                ('premier', models.BooleanField(default=False)),
                ('cliente_importante', models.BooleanField(default=False)),
                ('riesgo_flag', models.BooleanField(default=False)),
                ('bucket_q', models.CharField(blank=True, default='', help_text="Buckets: '1', '2', '3', '4-5', '6+'", max_length=10)),
                ('deuda_vs_costo', models.DecimalField(blank=True, decimal_places=4, help_text='deuda_total / costo_mensual (si costo > 0)', max_digits=18, null=True)),
                ('lote_ref', models.CharField(blank=True, default='', help_text='Identificador de lote/origen', max_length=100)),
            ],
            options={
                'verbose_name': 'ART Dashboard (Contrato-Período)',
                'verbose_name_plural': 'ART Dashboard (Contrato-Período)',
                'indexes': [models.Index(fields=['periodo'], name='art_artdash_periodo_a54b20_idx'), models.Index(fields=['aseguradora'], name='art_artdash_asegura_c6d57e_idx'), models.Index(fields=['productor'], name='art_artdash_product_72a7d2_idx'), models.Index(fields=['riesgo_flag', 'aseguradora'], name='art_artdash_riesgo__89a7cd_idx'), models.Index(fields=['bucket_q'], name='art_artdash_bucket__09e31e_idx'), models.Index(fields=['premier'], name='art_artdash_premier_27c6a8_idx'), models.Index(fields=['cliente_importante'], name='art_artdash_cliente_bcb7b2_idx')],
                'constraints': [models.UniqueConstraint(fields=('periodo', 'cuit', 'contrato', 'aseguradora'), name='uniq_art_dash_periodo_cuit_contrato_aseguradora')],
            },
        ),
    ]
