"""
Django settings for cobranzas_project project.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os  # Para variables de entorno

# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------
# Seguridad
# ---------------------------------------------------------------------
# Clave secreta (usar variable de entorno en producción)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-replace-me")
# DEBUG (en producción debe ser False)
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# Hosts permitidos (incluye tu IP pública para acceso externo)
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "192.168.50.66",  # IP local (tu máquina)
    "172.25.48.1",    # IP virtual/VPN si aplica
    "190.2.6.169",    # ← tu IP pública
]

# ---------------------------------------------------------------------
# Apps instaladas
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Proyecto
    "core",
    "gestion_cobranzas",
    "art",

    # Utilidades
    "django.contrib.humanize",
    "django_celery_results",
]

# ---------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ---------------------------------------------------------------------
# URLs / WSGI
# ---------------------------------------------------------------------
ROOT_URLCONF = "cobranzas_project.urls"
WSGI_APPLICATION = "cobranzas_project.wsgi.application"

# ---------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Plantillas globales (dejamos apuntando a core/templates según tu estructura)
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ---------------------------------------------------------------------
# Base de datos
# ---------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "cobranzas_db"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),  # definilo por variable de entorno
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# ---------------------------------------------------------------------
# Password validators
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------------------------------------------------
# Internacionalización / formato AR
# ---------------------------------------------------------------------
LANGUAGE_CODE = "es-ar"
TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_I18N = True
USE_TZ = True

# Formato numérico argentino
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = "."

# ---------------------------------------------------------------------
# Archivos estáticos
# ---------------------------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = []  # agregá carpetas locales si corresponde

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------
# Config específica del proyecto (ART)
# ---------------------------------------------------------------------
ART_ASEG_DIR = Path(r"C:/Users/Promecor/Documents/ART/Aseguradoras")
ART_MAESTRO_PATH = Path(
    r"C:/Users/Promecor/Documents/Aplicativo cobranzas/ART/TOTAL PARA SUBIR DEUDAS ART.xlsx"
)

# ---------------------------------------------------------------------
# Celery / Redis
# ---------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# ---------------------------------------------------------------------
# Email (SMTP Gmail via App Password)
# ---------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")            # tu cuenta Gmail
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")    # App Password (16 dígitos)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ---------------------------------------------------------------------
# Login / Logout
# ---------------------------------------------------------------------
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/dashboard/"       # coincide con core/urls.py
LOGOUT_REDIRECT_URL = "/accounts/login/"

# ---------------------------------------------------------------------
# (Opcional) CSRF para dominios/puertos externos
# ---------------------------------------------------------------------
# Si servís desde tu IP pública con HTTP, podés agregar (descomentando y ajustando):
# CSRF_TRUSTED_ORIGINS = [ "http://190.2.6.169:8000" ]
