# Generated by Django 5.2 on 2025-04-16 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogCargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('aseguradora', models.CharField(max_length=100)),
                ('ramo', models.CharField(max_length=100)),
                ('poliza', models.CharField(max_length=100)),
                ('endoso', models.CharField(max_length=100)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('archivo', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endoso', models.CharField(max_length=50)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cobranzas.aseguradora')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vencimiento', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gestion_cobranzas.planpago')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cobranzas.aseguradora')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cobranzas.ramo')),
            ],
            options={
                'unique_together': {('numero', 'aseguradora', 'ramo')},
            },
        ),
        migrations.AddField(
            model_name='planpago',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cobranzas.poliza'),
        ),
        migrations.AddField(
            model_name='planpago',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cobranzas.ramo'),
        ),
    ]
