# Generated by Django 5.2 on 2025-04-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpago',
            name='moneda',
            field=models.CharField(choices=[('$', 'Pesos'), ('U$S', 'Dólares')], default='$', max_length=4),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='endoso',
            field=models.CharField(max_length=20),
        ),
    ]
