# Generated by Django 5.2 on 2025-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranzas', '0002_planpago_moneda_alter_planpago_endoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='importe_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
