# Generated by Django 5.2 on 2025-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranzas', '0004_logimputacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='monto_imputado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
