# Generated by Django 5.2 on 2025-08-01 17:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranzas', '0005_cuota_monto_imputado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocklistEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioDeudaART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_archivo', models.DateField()),
                ('hoja', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'ERROR')], default='OK', max_length=10)),
                ('detalle_error', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=200)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ContratoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=120)),
                ('cuit', models.CharField(max_length=20)),
                ('aseguradora', models.CharField(max_length=60)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('q_periodos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('intimado', models.BooleanField(default=False)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion_cobranzas.enviodeudaart')),
            ],
            options={
                'ordering': ['contrato'],
            },
        ),
    ]
