# Generated by Django 5.2 on 2025-08-10 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranzas', '0006_blocklistemail_enviodeudaart_contratoenviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistemail',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contratoenviado',
            name='q_periodos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enviodeudaart',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_deuda_art', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enviodeudaart',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='enviodeudaart',
            name='fecha_archivo',
            field=models.DateField(help_text='Mes/año del Excel (01-2025)'),
        ),
        migrations.AlterField(
            model_name='enviodeudaart',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterModelTable(
            name='blocklistemail',
            table='gestion_cobranzas_blocklistemail',
        ),
        migrations.AlterModelTable(
            name='contratoenviado',
            table='gestion_cobranzas_contratoenviado',
        ),
        migrations.AlterModelTable(
            name='enviodeudaart',
            table='gestion_cobranzas_enviodeudaart',
        ),
    ]
