table QA_Control_CRM
	lineageTag: 8f311f1c-37f0-47cf-8862-5e38545dd5ee

	column tabla
		dataType: string
		lineageTag: 3f84fa34-5baf-434a-bf5a-72a98170be69
		summarizeBy: none
		sourceColumn: tabla

		annotation SummarizationSetBy = Automatic

	column filas
		dataType: int64
		formatString: 0
		lineageTag: 4ec1161e-271a-47e3-aa67-f9a912269fde
		summarizeBy: sum
		sourceColumn: filas

		annotation SummarizationSetBy = Automatic

	column max_created_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: cc8c6f79-b253-41e1-84fc-4cefec37d80a
		summarizeBy: none
		sourceColumn: max_created_utc

		variation Variación
			isDefault
			relationship: e9666d87-39d3-4f85-a17c-2c220833416e
			defaultHierarchy: LocalDateTable_fcb29007-0644-4fb0-af9b-a2d75bd3eb6e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column max_modified_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: ad0791b6-a1b5-4d60-b0f8-d7b00bf53f84
		summarizeBy: none
		sourceColumn: max_modified_utc

		variation Variación
			isDefault
			relationship: d2a5408d-8502-42e6-89a9-509453410901
			defaultHierarchy: LocalDateTable_76bb7131-aacd-4f84-a83b-a75dbb2c9dbd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column max_modified_ar
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c14633f-ddb9-434f-bab7-7c2ee16f7d4b
		summarizeBy: none
		sourceColumn: max_modified_ar

		variation Variación
			isDefault
			relationship: e9248ec5-60f7-4474-88bf-2b245cd50b82
			defaultHierarchy: LocalDateTable_88f1f22e-c20d-4db5-90cd-f7a4d54ad543.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition QA_Control_CRM = m
		mode: import
		queryGroup: QA
		source = ```
				let
				    // Referencias a las consultas de ORIGEN (tal como se llaman en tu lista)
				    Accounts = #"public crm_accounts",
				    Contacts = #"public crm_contacts",
				    Deals    = #"public crm_deals",
				
				    // Función que resume filas y máximos por tabla (intenta mantener el folding)
				    Agg = (tbl as table, name as text) as table =>
				        let
				            g = Table.Group(
				                    tbl, 
				                    {}, 
				                    {
				                        {"filas", each Table.RowCount(_), Int64.Type},
				                        {"max_created_utc",  each List.Max([created_time]),  type nullable datetimezone},
				                        {"max_modified_utc", each List.Max([modified_time]), type nullable datetimezone}
				                    }
				                ),
				            conNombre = Table.AddColumn(g, "tabla", each name, Text.Type),
				            reord     = Table.ReorderColumns(conNombre, {"tabla","filas","max_created_utc","max_modified_utc"}),
				            conAR     = Table.AddColumn(
				                            reord, 
				                            "max_modified_ar", 
				                            each try DateTimeZone.SwitchZone(DateTimeZone.From([max_modified_utc]), -3) otherwise null, 
				                            type nullable datetimezone
				                        )
				        in
				            conAR,
				
				    T1 = Agg(Accounts, "crm_accounts"),
				    T2 = Agg(Contacts, "crm_contacts"),
				    T3 = Agg(Deals,    "crm_deals"),
				
				    Control_CRM = Table.Combine({T1, T2, T3})
				in
				    Control_CRM
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

